'use client'

import Link from 'next/link'
import { ArrowLeft, Minus, Plus, ShoppingBag, Trash2 } from 'lucide-react'
import { useCart } from '@/components/cart-provider'
import { formatProductPrice, getProduct } from '@/lib/products'

export default function CartPage() {
  const { items, updateQuantity, removeItem } = useCart()
  const rows = items.map((item) => ({ item, product: getProduct(item.productId) })).filter((row) => row.product)
  const total = rows.reduce((sum, row) => sum + (row.product?.priceInCents ?? 0) * row.item.quantity, 0)

  return <main className="min-h-screen bg-slate-50 px-4 py-10 sm:px-6 md:py-16"><div className="mx-auto max-w-5xl"><Link href="/" className="inline-flex items-center gap-2 text-sm font-semibold text-blue-600"><ArrowLeft size={16} /> Continue shopping</Link><div className="mt-8 grid gap-8 md:grid-cols-[1fr_340px]"><section><div className="flex items-end justify-between"><div><p className="text-sm font-bold uppercase tracking-[0.18em] text-blue-600">Your selection</p><h1 className="mt-2 text-4xl font-bold text-slate-950">Shopping cart</h1></div><span className="text-sm text-slate-500">{items.length} service{items.length === 1 ? '' : 's'}</span></div>{rows.length ? <div className="mt-6 space-y-4">{rows.map(({ item, product }) => <article key={item.productId} className="flex flex-col gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-bold text-slate-950">{product?.name}</h2><p className="mt-1 text-sm text-slate-500">{product && formatProductPrice(product)} per service</p></div><div className="flex items-center justify-between gap-5"><div className="flex items-center rounded-xl border border-slate-200"><button aria-label="Decrease quantity" className="p-2" onClick={() => updateQuantity(item.productId, item.quantity - 1)}><Minus size={16} /></button><span className="w-8 text-center text-sm font-bold">{item.quantity}</span><button aria-label="Increase quantity" className="p-2" onClick={() => updateQuantity(item.productId, item.quantity + 1)}><Plus size={16} /></button></div><button aria-label={`Remove ${product?.name}`} className="text-slate-400 hover:text-red-500" onClick={() => removeItem(item.productId)}><Trash2 size={18} /></button></div></article>)}</div> : <div className="mt-8 rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><ShoppingBag className="mx-auto text-cyan-500" size={38} /><h2 className="mt-4 text-xl font-bold text-slate-950">Your cart is empty</h2><p className="mt-2 text-slate-600">Choose a service to start your order.</p><Link href="/services" className="mt-5 inline-flex rounded-xl bg-blue-600 px-5 py-3 font-bold text-white">Browse services</Link></div>}</section>{rows.length > 0 && <aside className="h-fit rounded-2xl bg-slate-950 p-6 text-white"><p className="text-sm text-slate-300">Order total</p><p className="mt-2 text-4xl font-bold text-cyan-300">£{(total / 100).toFixed(2)}</p><p className="mt-3 text-sm leading-6 text-slate-400">Secure card checkout powered by Stripe.</p><Link href="/checkout" className="mt-6 flex w-full items-center justify-center rounded-xl bg-cyan-400 px-5 py-3 font-bold text-slate-950 hover:bg-cyan-300">Continue to checkout</Link></aside>}</div></div></main>
}
